### ISSUE TITLE
research tool simple and sesy to implement improvements

### ISSUE THREAD

**Issue by shvahabi** [ReDEnergy/SessionSync#101]
By adding simple features this very useful add-on will go beyond session management, to a basic research tool:
- Instead of saving sessions in bookmark folders, there shall be an option, to save sessions by adding session names as bookmark tags. Flat classification by tags has many advantages over hierarchical ones, and user shall have the freedom to opt, while it is already implemented in firefox.
- Any session name, shall have a descriptive note as well as name. Names are titles with a phrase-like structures, but notes can be used to document a research idea which lead to that set of pages or any other useful information.
- By using google search engine APIs, a search term could be restricted to searched within only a saved session pages. A user who don't remember where exactly he studied some fact, but has related pages all gathered in a specific session, can search confined within that specific session for the exact page, otherwise the same search term in google gives lots of results and the user cannot decide which page was the one he studied earlier.

**Comment by ReDEnergy** [comment]
Hi, sadly things are way complicated that they look, not because I don't want to add certain features but because the API is stupid and primitive and Mozilla wants to be in line with Chrome, which means that a lot of good historic features that Mozilla had can't be used at all.

1.WebExtension API does not offer any way to interact with bookmark tags... end of story. There's nothing I can do as a developer for that.
2. Saving the description into bookmarks is not possible because a folder has only a "title" entry available. Anything else I would save is not really persistent into bookmarks and synchronization across multiple instances is really problematic.
3. This sound more like a complete new addon that a feature. And since everything saves can be found in bookmarks it can be implemented that way. That being said, although I can see why this might be useful I clearly don't a feature like this one in mind for the next period.

**Comment by shvahabi** [comment]
Hi, OK. Still you did a great job providing SessionSync, even if my requested features are not possible to implement or are not fit in your intended way of evolution for SessionSync. By the way thanks for your attention and detailed explanations.
