### ISSUE TITLE
Firefox 86: scrolling in SessionSync popup is broken

### ISSUE THREAD

**Issue by charlieok** [ReDEnergy/SessionSync#103]
After updating to Firefox 86, I am unable to scroll using either a mouse wheel or touchpad in the SessionSync popup.

I see an issue was filed when Firefox 86 was in the Nightly channel:

https://github.com/ReDEnergy/SessionSync/issues/100

That issue was closed a few days later by the person who filed it, with a note that it might apply to extensions generally rather than SessionSync specifically. After testing that idea a bit I can say that scrolling works fine for me in some other similar extension popups, such as Multi-Account Containers and SEOInfo, and thus far I've only noticed a scrolling problem for SessionSync.

**Comment by ReDEnergy** [comment]
God... I really wish Firefox would not break so many things after each update :|.
The problem is like this. That specific panel is actually built using 100% HTML/JavaScript/CSS code. There can't be a problem with how the panel is build suddenly. I have Firefox 87 and works as intended, and used it on Firefox 86 a lot without any issues.
What exactly does not work in your situation really beats me. Is not like I've implemented any kind of special scrolling inside the panel... the scrolling is provided by the browser itself because the content is greater than the viewing area.
Sadly, there's not really something that I can go and fix about this. I haven't implemented any scrolling so there's nothing to check/fix and I sincerely have no idea where to start looking for such a problem. I do understand it's happening only in the case of my addon but the reason is still somehow the browser itself, or something from the profile files.

Ideas to check:
 - just uninstall the addon, restart firefox, install it again (saved session as bookmarks will not be affected because they are stored in bookmarks)
 - see if then using the other 2 views things works as intended (CTRL + SHIFT + V) and window-view

Sorry for not having a solution but the bug is simply something like... The browser does not act as it's suppose to. It's impossible for me to check and find a solution for a feature offered by the browser itself.

![image](https://user-images.githubusercontent.com/1395510/109136615-fa9b9c80-7760-11eb-8d17-82a84bd38c40.png)

**Comment by charlieok** [comment]
Ok. First off, thank you very much for making this extension. The fact that its backing store is the browser's bookmarks (which can be synced between installs on multiple machines) is a nice approach, and is one of the main reasons I decided to use the extension in the first place.

In my time using SessionSync I have gone from not really using the browser's bookmarks at all to amassing over 77000 bookmarks and counting. I realize I may be pushing the tool way past what you thought anyone would do, but that's a sign of just how useful it has become to me. That means many operations involve some delay now, but I was tolerating that because I have not figured out what a better setup would be or how I would migrate all that data once I found one. (I'm staring to think about the possibility of syncing between a SessionSync bookmark folder and a site like pinboard or instapaper or pocket. Don't know if those data models would map well bidirectionally or not).

With the scrolling issue, I am unable to find things unless I remember exactly what I'm looking for with enough specificity to narrow the displayed items to the point where no scrolling is necessary to see the item. So anything that would provide another way to scroll the view would make it at least usable again. For example, if up/down arrow keys could move the item selection up and down, maybe that would allow the view to move and things outside the current view would again be reachable.

Meanwhile, I will try your uninstall/reinstall suggestion and see if that make a difference, and report back.

**Comment by charlieok** [comment]
I've just uninstalled the extension, quit firefox, restarted firefox, and reinstalled the extension. Still no scrolling unfortunately :(

**Comment by charlieok** [comment]
ok after looking around a bit through the settings I see I can detach the popup into its own window. I was unfamiliar with this option. Maybe I missed it or maybe it wasn't there when I first set it up and was added in a later version. In any case, scrolling works in the detached window mode so my immediate usability problem is solved. It also solves some other problems I was having, like getting a bigger working area, and not incurring a delay each time I open the popup.

Thanks again for the great extension!

**Comment by bayeslearner** [comment]
I can confirm I have the same issue.  Detaching as a popup seems to get around it.

**Comment by charlieok** [comment]
I'm now running Firefox 88.0 (on Big Sur 11.2.3 in case that matters) and I noticed that I can scroll in the Session Sync toolbar popup again! That completely fixes this for me. Maybe Firefox made a change that fixed it? Not sure.

As far as I am concerned this issue can now be closed but rather than just click 'close' right now I'll leave it to the maintainer to decide how to handle it from here.
