### ISSUE TITLE
Sessions won't save at all - just create empty sessions

### ISSUE THREAD

**Issue by davidjade** [ReDEnergy/SessionSync#104]
When I open the add-on and click the save session button, it prompts to create a new session and initially shows all the bookmarks but there are not really there. if I select another session and then go back to the one just created, it is now empty. Furthermore, if I find the session in the regular FF bookmark folder, that folder is completely empty.

It is failing to do the most basic thing - save a session.

**Comment by ReDEnergy** [comment]
Sorry to hear that. Sadly I can't pinpoint an issue for this because there might be something wrong with the Firefox profile itself. The addon should work as intended and it does work for thousands of users. Of course, there may be various issues that user face from time to time but those are not triggered but any kind of bug inside the addon itself sadly. Most of them are because of a corrupted profile session sadly and that I can't fix.
On an clean profile, I guarantee that the issue will not happen at all. So although you have an issue, sadly this kind of issues with incorrect saving most probably are not cauzes by the addon itself.

**Comment by davidjade** [comment]
It is very odd but I think there is a conflict with another bookmarking add-on. I'm going to close this as it maybe appears to be specific to my set of add-ons.
