### ISSUE TITLE
Scrolling no longer working on Firefox 87.0 on MacOS Catalina 10.15.7

### ISSUE THREAD

**Issue by jpganucheau** [ReDEnergy/SessionSync#106]
Scrolling no longer works for sessions or links within sessions. Only changing sorting on sessions will change their order. Mouse scroll, touchpad, and keyboard arrows all do not scroll now.

**Comment by ReDEnergy** [comment]
Sorry for the issue but sadly the bug is not created by the addon. Please read more detailed information in #103 . Will be closing this one since it's a duplicate.
Again, it would be the first thing I would solve if I could do that, simply I have no idea why it's happening and its 100% not generated by the addon code but by something from Firefox or WebExtensions API.
