### ISSUE TITLE
pop up size is too small, and not resizable, when pinned to overflow menu.

### ISSUE THREAD

**Issue by onguarde** [ReDEnergy/SessionSync#121]
![image](https://github.com/ReDEnergy/SessionSync/assets/681355/a3d439d4-a446-48aa-a7af-61e17dabbdf1)

I believe this is a bug. I'm not able to resize it to be bigger even when using the resize handler in the left bottom corner. 

When I don't pin to overflow menu, the size is fine, so that's my workaround...

![image](https://github.com/ReDEnergy/SessionSync/assets/681355/4452eaf7-d366-4f37-914c-c0b8f140f2dc)

**Comment by ReDEnergy** [comment]
As much as I would like to make it bigger Firefox does not allow this. Simply put, Firefox developers don't want that panel to be more than what you see there. It really annoys me but I can't do anything about this. That's why I offer the option to open the page in a separate Window (CTRL + SHIFT + Y) or in a tab.
