### ISSUE TITLE
Replicate the behaviour of "Don't load tabs until selected" when restoring a session

### ISSUE THREAD

**Issue by fturcheti** [ReDEnergy/SessionSync#13]
Is it possible to replicate/respect the behaviour of "Don't load tabs until selected" when restoring a session?

As I have "Don't load tabs until selected" enabled, when restoring a session, in the current window or in a new one, I'd expect all the tabs to be created but only the last one, the selected, to be loaded.

**Comment by ReDEnergy** [comment]
Yes, this would be a very nice feature because it will also improve the performance. Sadly at this moment I'm unaware of any possibility to do that using native SDK code but I think I have found a workaround for it. I'm writing it here to be sure I won't forget it

**Possible Workaround**  
- load all tabs as plain tabs
- change title of each tab according to each urls that was supposed to be opened
- attach a script or an event on the tab as when it is activated to be redirect to the expected tab

There isn't such thing as a selected tab when restoring a session so I guess I will have to decide which one it will be loaded. Probably the last one it's fine because it will be the active tab.

**Comment by ReDEnergy** [comment]
Fixed in release v2.0.1
  - when restoring many tabs, tabs will be loaded only when activated
  - functionality implemented exactly like the workaround stated in the comment above
  - greatly improved performance when dealing with tens of bookmarks
