### ISSUE TITLE
Pale Moon

### ISSUE THREAD

**Issue by linuxrocks123** [ReDEnergy/SessionSync#14]
Session Sync cannot be installed on Pale Moon, a fork of Firefox: http://www.palemoon.org

Attempting to install the addon just gives a message from Pale Moon saying "This addon is not compatible with Pale Moon 25.8.1."  It may be that there's an actual problem, or it may be that the metadata for the addon just needs to be changed.

I know Pale Moon compatibility probably isn't a terribly important feature for you to add, but, if it's an easy fix, I'd appreciate your taking the time to look into it.  It looks like an awesome addon.  Let me know if you'd like me to test anything.

**Comment by ReDEnergy** [comment]
Hi. Most probably the problem is in the configuration install file because I see no reason why there will be a problem with the code. I will try to fix it. I will get back with an answer.

**Comment by ReDEnergy** [comment]
Hi. I managed to installed it but its no use. Because I uses a static XUL insertion and Pale Moon is quite different from standard Firefox it won't work at all. Also I get some errors and the source seem to be  the Addon-SDK itself (maybe it's an older version in Pale Moon). Sorry but I won't be able to provide compatibility for Pale Moon.

**Comment by ReDEnergy** [comment]
Until Session Sync can be ported to web-extension most probably support for other browser won't be available
