### ISSUE TITLE
Pinned Tabs aren't saved as such

### ISSUE THREAD

**Issue by Backfighter** [ReDEnergy/SessionSync#16]
It would be nice if pinned tabs are saved as such so that they can be restored as pinned tabs when a session is being loaded.

**Comment by ReDEnergy** [comment]
If the API will permit this I will do it since is not nice to change the session state when saving/restoring it.

**Comment by thomasgauthier** [comment]
Could https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/tabs#isPinned be used for that?

**Comment by ReDEnergy** [comment]
Hi. Thank you for point it out. There was never a problem with information whether a tab is pinned or not, but mostly to how should I provide a sync feature inside the bookmarks to maintain the "pinned" status. Anyway I can gladly say that I solved the problem it works perfectly and also has some configuration regarding this pinned status.

**P.S** Sadly It took me longer than I expected (way way to long) to get everything ready for the new version. I hope to finish it this week or the next one. If you want I can provide an unsigned version that already has this implementation with rough edges but it works fine (only you're using Firefox Developer Edition, otherwise you won't be able to install it). If not, please wait for the next update, I can guarantee that it will happen this week or later the next one.

**Comment by thomasgauthier** [comment]
Ok, glad you got it working. There's no hurry, I'll wait for the official update!

**Comment by ReDEnergy** [comment]
Fixed in latest release v2.0.1
 - added setting to save or ignore pinned tabs
 - pinned state can be saved or not when saving a certain session
 - tab pin state is sync along with the bookmark item
 - when restoring pinned _bookmarks_ are restored as pinned tabs
