### ISSUE TITLE
Removing entries in a session is to clumsy

### ISSUE THREAD

**Issue by Backfighter** [ReDEnergy/SessionSync#17]
Needing to perform a right-click on every entry and even confirm to delete makes removing several entries time consuming. 

Suggestion
It would be nice if there was a [x] button on the right of each entry to be able to easily delete them. In addition a functionality to undo the delete if it was trigger accidentally  would make up for the confirm message.

**Comment by ReDEnergy** [comment]
Probably I will add an option to show/hide the delete button.
Since I had not time to implement a complete undo-history I had to add the confirmation modal. When 
The **undo** functionality is a must and when it will be ready the confirmation will be removed.
UI 2.0 will also permit to remove a bookmark using drag-n-drop, by dropping it in a certain **delete zone**. It's already implemented on the experimental API, you can find the download page in the README.

**Comment by ReDEnergy** [comment]
Fixed in latest release.
 - can use **drag-n-drop** to delete items or **right-click delete** without confirmation
 - added **undo** action for restoring deleted items
