### ISSUE TITLE
Port SessionSync to WebExtension API

### ISSUE THREAD

**Issue by FlorianFranzen** [ReDEnergy/SessionSync#25]
Mozilla plans to fully switch to WebExtension in November, at which point you can no longer use this plugin in newer versions of Firefox.

What are the plans for and the state of a WebExtension port? 

Can the full functionality be preserved using only the WebExtension API?

**Comment by ReDEnergy** [comment]
The addon will definetely be ported to WebExtension (at this point it has become an essential part of my browsing experience and once WebExtension will hit the Release channel I will need it for sure. Of course there are still more than 1500 users that find it useful so clearly I want it to continue to be like that)
Sadly, certain features will be missing and the overall experience will be less satisfying than what it offers right now, but the essential features will remain and I hope people will still find it as useful.
Since Mozilla decided to kill the innovation (through custom advance extension) the only way I can preserve the addon is like this.
 - the bookmark panel will be moved to the right-top area. It will be maximum size of 800 x 600 (because clearly someone from Mozilla doesn't know what year we're living and and for them enforcing a stupid resolution is fine)
 - there's absolutely no way of providing support for Pin Tabs or Folder description (I hope not may users need that)
 - there will some limitations with drag n drop features (Trash can to delete bookmakrs for example will have to be either moved or not implemented at all)
 - less UI space for some users since the resolution is hard limited by the API

Other than that. Critical features like session bookmark management and session saving should be preserved the way they are right now. I will try to do my best to finish the update by 15 November when Firefox 57 will be released.

Regarding development status. The code is really well built around the old API and I know I will have some challenges to pass in order to be able to fully update 

So the plans are like that. Even if there is not a single person using the addon I will still port it because it's more than essential for me :). On a bonus side I might also make it available for Chrome but it will live as a different addon. Of couse, as long as cross browser bookmark synchronization is done using a certain service it should be able to be used as a cross-browser management tool.

**Comment by FSMaxB** [comment]
Any estimate on when the port will be ready?

**Comment by ReDEnergy** [comment]
As much as I would love to say that very soon, the truth is that I was not able to port it till now. I can't tell you exactly how fast I can get it working. I will definitely do this as soon as possible because essentially I had to rollback today to Firefox ESR just for continuing to use it. Probably I will need at least 2 more weeks. Sorry for all the inconvenience created.

**Comment by FSMaxB** [comment]
Workaround for people that want to use FF57 and not lose all their tabs:

For the transition period I am using [Tab Session Manager](https://addons.mozilla.org/en-US/firefox/addon/tab-session-manager/), there is a gotcha however when using it to transition a session from FF56 to 57, see https://github.com/sienori/Tab-Session-Manager/issues/32. Also it seems like all tabs have to be loaded before saving a session, otherwise they will be lost.

**Comment by masaeedu** [comment]
@ReDEnergy Is there anything I can help out with here? Perhaps it would be useful to have a checklist of tasks to complete.

I use the extension for day to day browsing and now that 57 is GA-ed all my firefox versions are starting to turn into 57, which doesn't support session sync.

**Comment by ReDEnergy** [comment]
@masaeedu Sorry to hear that. I know that it's not optional but in case you really need it working there is only one solution Firefox ESR (https://www.mozilla.org/en-US/firefox/organizations/all/) at least until I will update the Webextension version. Will try to make it as soon as possible.

**Comment by agadino** [comment]
@masaeedu I temporarily solved by installing a previous portable Firefox version, so it can coexist with the standard new version.. I'll keep the portable one until the addons (at least, the ones I use the most) will be uptaded

**Comment by agadino** [comment]
@ReDEnergy just want to thank you for your efforts.. hope the SessionSynch will soon be available again, I find it very very useful

**Comment by ReDEnergy** [comment]
Fully signed WebExtensions is ready and can be installed manually (see README)
This is the final release intended for AMO but in order to make sure that there are no critical issues I'll test it for one more week before full AMO release.

**Comment by ReDEnergy** [comment]
WebExtensions port ready (477ca83) and available on [AMO](https://addons.mozilla.org/en-US/firefox/addon/session-sync/). Thanks for all the support

**Comment by xakraz** [comment]
Hello !

Sorry to dig out this issue 😅 what about the port to Google Chrome ?

**Comment by ReDEnergy** [comment]
@xakraz Sadly there are quite a few reasons I don't think I will be doing that too soon.
1. Chrome has Session Buddy which seems to be always a constant comparison with my implementation (mostly because I have missing feature X and Y that Session Buddy has) although Session Sync is build with a complete different approach in mind and it's not really fair to compare them
2. At the same time Session Buddy being extremely popular competing with it is almost impossible, not that I gain anything by competing with other extensions but at least if you invest the time into development 
3. Sync will not work cross-browser unless a cross-browsing bookmark sync solution will be used - think EverSync does that
4. Sadly Chrome has a a slite different API that prevents me to just take the code and test it on Chrome, so it's not that straight forward to port it like I wished even though is was suppose to be the same WebExtensions API. There seems to be a solution that makes things easier to port [webextension-polyfill](https://github.com/mozilla/webextension-polyfill) everything but I have to check it out first
5. It may not make much sense for some people but I'm kind of a Firefox promoter myself and I have no intention whatsoever to help user chose Chrome over Firefox. At the same time Session Sync was never build to keep you on the Firefox ecosystem (I don't think that would be normal either), everything is there in plain view, you can move the bookmarks whenever you want between browsers so I guess it's perfectly acceptable.
6. Time is quite precious and lately I barely had time to fix some issue let alone to add support for missing feature that many user expect to be present. Of course that doesn't mean I'm stopping support of the addon, that's clearly not the case, it's one of my most important projects and that will remain for a very long time since it's quite critical for my daily browsing experience and I might assume for others as well but since it mostly covers 95% percent of what most need (at least that's my case) I had slowed down on the updating part solely because for the last 2+ years I've been working on a different project that took over all my free time (a complex 3D RPG game that I expect to sell at some point so let's just say it's my priority for the moment)
7. I can't say for sure I don't plan ever to bring support to Chrome, it just that I have almost no reason (points 1-5) and time to do so at this point.

**Comment by xakraz** [comment]
@ReDEnergy Very fair points.

🙏 for your time explaining it, I totally understand.

**Comment by smaragdus** [comment]
@ReDEnergy 

I hope that you may change your mind in the future and port [Session Sync](https://addons.mozilla.org/en-US/firefox/addon/session-sync/) to Chromium if time permits. After having Firefox as default browser for more than a decade I finally switched to a Chromium fork as my patience for Mozilla nuisances was completely exhausted. Nowadays I use a Firefox fork just to test extensions unavailable for Chromium. There are several acceptable alternatives available for Chromium but none of them is as pretty as [SessionSync](https://github.com/ReDEnergy/SessionSync), I really like its interface.
