### ISSUE TITLE
Quamtum update?

### ISSUE THREAD

**Issue by xulianh** [ReDEnergy/SessionSync#27]
It's disabled after Firefox updated to latest version

**Comment by ReDEnergy** [comment]
Sorry about it. I'm still working on porting it to WebExtensions API.

**Comment by xulianh** [comment]
Thanks for your feedback Gabriel

**Comment by Matt-Deacalion** [comment]
This is the best session manager I've used by far, very happy you're still working on it!

**Comment by ReDEnergy** [comment]
Time flies. There are already more than 2 months since I said that there will be a port. Yes, it didn't happen and can't say anything else than I'm sorry for promising and not delivering, but the port is definitely happening (Of course, the reason why is not ready is quite obvious, I was not able to work on it for a while but I should will resume the work in a week). By the end of the month I hope to have it updated.

**Comment by agadino** [comment]
Thank you for your effort, Gabriel.. looking forward to use the SessionSync again

**Comment by ReDEnergy** [comment]
Fully signed WebExtensions is ready and can be installed manually (see README)
This is the final release intended for AMO but in order to make sure that there are no critical issues I'll test it for one more week before full AMO release.

**Comment by agadino** [comment]
Yeah!! Here it is again!! Fantastic news today.. thank you!!

**Comment by Matt-Deacalion** [comment]
Working fine on Firefox Developer Edition 59. Kudos to you for the work that has gone into this!

**Comment by neeraj-m** [comment]
Working great! The only minor bug I've found is that when SessionSync is pinned to the overflow menu instead, the SS window is forced to a size which is too small to access all the available options and view details. 
Simply fixed by unpinning from the overflow
Thanks for all the hard work!

**Comment by ReDEnergy** [comment]
This is the Overflow menu no ? Yes that one won't work ok.
![image](https://user-images.githubusercontent.com/1395510/37475966-9a198466-287c-11e8-8b56-62bf1d9243b3.png)

Not sure I can even make sure by default the addon will not be placed there. WebExtensions API is so dumb (that not to say the one that actually built it) that there are actual size limits everywhere and even for the normal widow you can't go over 800 x 600 pixels for the addon window. How will this look on a 4K display with native resolution... probably not that good but some smart guys at Mozilla think it's fine to put a stupid hard limit to any UI size.

Thanks for the feedback. I will look to find a solution to force the move outside of the Overflow Menu or at least display a warning... although I don't even thing there's a way to know where the addon sits on the UI.

**Comment by ReDEnergy** [comment]
Finally ... the oficial WebExtensions port version 3.0.0 is ready and can be downloaded from the [Official Addon Page](https://addons.mozilla.org/en-US/firefox/addon/session-sync/)
It has a bunch of improvements and features compared to the previous one (after 2 weeks of testing)  

**Thanks to everyone who supports the addon by using it, the community support was a really big push for me to actually do this**. Porting it was something that initially I thought it was impossible but somehow even on the limited WebExtensions API it can do most of the things it used to. Things will only get better with future versions.

**Comment by Matt-Deacalion** [comment]
I just had a look at 477ca83333886efc2d7ef5f5a4b1b408acd81d29, it must have taken a great effort on your part. Very lucky to have people who make tools as good as these, it's massively appreciated!

**Comment by ReDEnergy** [comment]
Well actually... that's only the last two-week push (and most of it were deleted stuff). The real WebExtensions port actually happened in a74dbc6. In total is something like this:
 * 9,945 additions and 3,745 deletions
 * 1,643 additions and 9,407 deletions. 
Of course... probably around 50% of those are not real changes but even so... I had to go over and edit more than 12K lines and add probably over 3-4 K for the WebExtensions API to work.
But in the end... got the Quantum speed long awaited as I was still using Firefox 56 in order to use my addon.
