### ISSUE TITLE
Feature request: Drag and drop from Active Session

### ISSUE THREAD

**Issue by alesmuc** [ReDEnergy/SessionSync#49]
Hi, from saved session I can drug and drom tabs to other saved session, but I cant drug and drop from Active session to saved session, for example to add active tabs to different saved sessions.
The way I do it now is: save the active session, go to the session just saved, drug and drop tabs to other saver session, delete the just saved session. It works, but is not confortable.
I also had some problem to find "Create new session" function, as I didn't aspect to find it in another saved session menù. I was tring to right click the empty space under the saved session, I thing it would be more intuitive.
Thank you for your beautiful extension :)

**Comment by ReDEnergy** [comment]
Well that's because I was in a hurry and didn't finish all the functionality for the drag-and-drop for active sessions. It will be implemented for sure in the next release.

Regarding the "Create new sessions"... well you're kinda right. But, not sure why did I removed the menu for the right click on empty space because I had that as well.
The way it works was like this:
  - empty space -> right click -> only the "Create new session" was displayed (but somehow this no longer works and thanks for the info because that's a bug)
  - when you don't have empty space (because after saving a few session you won't have enough space) you can click anywhere. This was mostly a solution for the problem with no enough space, never intended to be the main way of creating new sessions.

**Comment by alesmuc** [comment]
Thank you very much, good luck :)

**Comment by AnFlare** [comment]
I'd like to double this feature request.

**Comment by ReDEnergy** [comment]
Fixed as of Version 3.1.6 (ba7148a36d098080312c6753534a26565ba8e60f)
