### ISSUE TITLE
Edit Title label doesn't work on FFv52 or v56

### ISSUE THREAD

**Issue by dapgo** [ReDEnergy/SessionSync#55]
I tried to rename the default title based in date but the renaming are is not displayed at the bottom. 
However, I checked also with FF v6x, and the result is different. After clicking on "Edit", an inputbox and two buttons are displayed at the bottom.

At least it fails on: FF55, Basilisk (based in ff52), Waterfox(based in FF56)

**Comment by dapgo** [comment]
On Basilisk browser console i can see:
Content Security Policy: The page’s settings blocked the loading of a resource at self (“style-src https://addons-amo.cdn.mozilla.net”).

**Comment by ReDEnergy** [comment]
Sincerely. From when I moved to WebExtensions API I didn't intended to keep backwards compatibility with versions lower than Firefox 57 since there were a lot of API that simply were never available on earlier version. Now, I'm wondering what version of the addon are you talking about? v2.0 (Addon SDK) or v3.0 (WebExtensions port) because from v2 to v3 there was a complete rewrite with many features missing that were available in v2. I suppose thate there are possibilities to be certain bugs on v2 but if we're talking about that, I simply don't have the time to keep that one up (updates and bugfixes). If you're talking about v3 on Firefox 55, or 56, I really don't know what is the status support for certain Webextensions features and that might prevent the addon from running as it suppose to. Sorry for the bad experience but I don't think I can do something about the support for older versions than Firefox 57. I kept the V2 support for almost half an year but then after I managed to port it to Webextensions I couldn't any longer because the code is almost completely different.
Thanks for understanding.

**Comment by dapgo** [comment]
I am speaking about v3.1.0, which says that works with Firefox for Android 48.0 and later, Firefox 42.0 and later)
Being compatible with FF56 webextensions API will allow the extension to run in mixed (XUL&webextension) browsers which are still actively supported. ;)
