### ISSUE TITLE
‘Show all windows’ toggle doesn't work

### ISSUE THREAD

**Issue by ethylmertz** [ReDEnergy/SessionSync#57]
Firefox 64.0 / macOS 10.14.2

I have this extension installed on 2 different Macs — same version of Firefox, same version of macOS (10.14.2) on both.

On one of the machines the ‘Show all windows’ toggle *works in the Session Sync window; on the other machine, it doesn't. I've tried deleting / reinstalling the extension on the non-working machine; didn't fix it — and the extension is obviously saving data & preferences after being deleted. So I deleted it again, and went into ~/Library/Application Support/Firefox... and rooted around for anything that had session sync in the name. Reinstalled the extension. No help — and it's still retrieving saved session data from the original install.

**Comment by ReDEnergy** [comment]
By not working:
 - when you open the panel does it show it is active or all the time is disabled no matter if you enable it (appears disabled after closing and opening again the interface)
![image](https://user-images.githubusercontent.com/1395510/50560833-3cf5fa00-0d0d-11e9-8323-c5ac043af8f6.png)
 - I mean it may help me to figure out if it's a settings saving issue or something else

> and it's still retrieving saved session data from the original install.
If you mean the manually saved sessions that's perfectly normal since those are saved in Bookmarks and even if you uninstall the addon the bookmarks will not be deleted. They can be found in `/Bookmarks Menu/Session Sync`

Sadly I don't think it's a problem with the addon. Although everything seems to be the same most probably it's something outside of the addon that causes that (not that I know exactly what). One thing that you can try is to overwrite the current install with an older version. That might delete the saved preferences from the addon, and then install the current version again.

https://addons.mozilla.org/en-US/firefox/addon/session-sync/versions/

Have you tried switch the toggle in the `Tab View` or `Window View` ?

Really sorry for the issues your experiencing. I will try to figure out what happens but it's not really an easy task. At least I will remember to add a reset configuration option in the addon so that might help if the feature with similar issues.

**Comment by ethylmertz** [comment]
Greetings — 

Thank you for the quick response.

To your first question: The ON/OFF toggle remains in the OFF position (on the “non-working” Mac)

I deleted the current version (using the REMOVE function) and installed the previous version — 3.0.3. The toggle switch *immediately started working (in Window mode). I then installed the current version 3.1.0 by overwriting the older version, and the toggle switch continued to work for a short time — but soon it started ’sticking’ on the OFF position (in Window mode). I tried invoking Tab mode at that point, and the toggle switch *seems to be working properly. But if I invoke the Window mode (while the Tab mode is open, and the toggle in the ON position) the toggle switch in the Window is *usually remains stuck in the OFF position, and is unresponsive…although *sometimes it responds, seemingly in a random fashion. 

Anyway, I appreciate your help, and hopefully the info provided above will help you troubleshoot this. It’s amazing how crappy all the other “session saver” extensions for Firefox are, and I appreciate that yours is much better than the others, even with this toggle-switch bug. FYI — I was a default-Safari user until version 12, and its deprecation of extensions — particularly the very beautiful Sessions https://sessions-extension.github.io/Sessions/ <https://sessions-extension.github.io/Sessions/>. I can’t live without a functional / customizable adblocker and the Ghostery extension, and I hate Chrome on the Mac (actually I hate anything Google), so Firefox is now my default browser.

I’ll look forward to future iterations of your extension. Thanks again, and have a very happy New Year — 

/ Grey Jensen

**Comment by ReDEnergy** [comment]
Thanks for the detailed information. I can't seem to replicate any of that behavior right now but I least I will look into it more to see if there's anything I can do. What's actually really strange is the fact that the code is virtually the same everywhere... I mean, all those different view modes run on the exact same code, and the fact that sometimes works in a certain mode and sometimes it doesn't it's pretty weird.
Thanks for using Firefox and the addon. Happy New Year.

**Comment by ReDEnergy** [comment]
Just a notice that my Firefox decided to trigger this bug suddenly. And that's great because I managed to find the issue. I already have a signed beta version and everything seems to be working fine. I will push the release later today after I make sure that everything else works as expected.

**Comment by ReDEnergy** [comment]
Should be fixed as of ba7148a36d098080312c6753534a26565ba8e60f
