### ISSUE TITLE
High RAM use

### ISSUE THREAD

**Issue by hervis73** [ReDEnergy/SessionSync#60]
Hello,

I am using your extension for a year and I really appreciate using it.

It seems however that your recent update provoked high peak use of RAM. I discovered it by following this [Mozilla support page](https://support.mozilla.org/en-US/kb/troubleshoot-extensions-themes-to-fix-problems) and isolate all of my extensions.
Since this update (3.1.3), I am immediately using 95% of my RAM (8GB) from Firefox launch and have some CPU spikes.

I am using Firefox 64.0.2 64 bits on Windows 7 x64

**Comment by ReDEnergy** [comment]
Oukey... I really wonder what on earth could have happened!
I mean the changes I did have nothing to do with memory use. I looked over again over the code there's simply no serious difference that may cause such thing.
By default... the only thing that may use any kind of resources during Firefox startup or inside the browser is the auto-save feature. That's the only thing that is active while the panel is closed. Otherwise all the code from the panel is actually initialized on demand every single time the panel is opened. And the only changes I did were related to that panel.
I don't have Window 7 but I can try to test as well on Firefox 64 on a clean profile. Is there something specific I have to do or simply just by having the addon installed I'm suppose to see this problem.

**Comment by ReDEnergy** [comment]
Can you please disable the auto-save feature and see if you still have the same error?
Just tested on my pc. Can tell that nothing special happens. No matter if the addon is enabled or disabled. As regarding cpu spikes.. that as well is really strange because the addon doesn't do anything in the background (outside of saving the session once every 15 seconds or whatever number have you set).

**Comment by ReDEnergy** [comment]
There has to be another explanation. Might be related somehow to the fact that I updated it but I definitely would say that it's impossible to be the addon itself. Have you tried uninstalling the addon and then test and then install it again?

**Comment by hervis73** [comment]
I tried to disable Autosave and it seems that it was the source of the problem. Here are some screens with CPU and RAM usages

The left part shows before I reactivate Session Sync. Firefox freezes occur sometimes:
![usageram](https://user-images.githubusercontent.com/46845733/51429038-da589580-1c0a-11e9-9bc7-3d8a660a070a.PNG)

After disabling Autosave, it is much better and stable (right part):
![afterdisablingautosave](https://user-images.githubusercontent.com/46845733/51429037-d9bfff00-1c0a-11e9-83c3-0dc12780728d.PNG)

I suspect that the problem may come from the number of opened tabs. I have hundreds of them opened (but unloaded). Maybe, it could be when favicons are downloaded for example?

**Comment by ReDEnergy** [comment]
Mmm... this is really stupid. I enabled the addon to download any kind of favicon even if it is a image and save it locally but I never expected such thing to happen. If I get you a signed update that fixes this would you test it for me ? I will only add that specific line I removed in this version.

**Comment by hervis73** [comment]
Sure, no problem.

It would arrange me, as I would rather keep using the autosave

**Comment by ReDEnergy** [comment]
This is it. It's signed and has only 3 lines changed from the previous version.
[Session Sync 3.1.4beta](https://www.dropbox.com/s/zopnpmysmj4mdms/session_sync-3.1.4beta-fx.xpi?dl=0)

**Comment by hervis73** [comment]
I tested it, but unfortunately, the issue is not solved. Maybe the problem comes from somewhere else.

**Comment by ReDEnergy** [comment]
Preparing a different one with possibility to disable the favicon-service from option panel. Will be back shortly.

**Comment by ReDEnergy** [comment]
Sorry that it took so long. If by any chance you can check this one as well that would be great.
[Session Sync 3.1.5beta](https://www.dropbox.com/s/l2qfmmz9r3sz04n/session_sync-3.1.5beta-fx.xpi?dl=0)
Please go to the options panel and disable the Favicon Service completely, and then check again. I really hope this one solves the problem so that at least I can figure out what is happening and where.
![image](https://user-images.githubusercontent.com/1395510/51430444-4267a580-1c24-11e9-9c81-710d48bc699e.png)
I will also try to figure out if I can replicate the same behaviour.

**Comment by hervis73** [comment]
I installed your version, disabled the favicon service and then enabled the autosave.
Unfortunately, the issue is still not solved.

Don't worry about my issue. It seems that I am the only one having it, according to this repository and the AMO page.

I emitted the hypothesis that it could be the favicons, because a similar problem happened for another extension (Onetab, no longer updated for a long time). But I am just a simple user, so I don't have much knowledge about the extensions running.

If you need more informations about my Firefox configuration, I could send it to you if you show me how it is done and if it may help you.

**Comment by ReDEnergy** [comment]
Well... based on what you tested there seems to be a certain issue somewhere but clearly is not easy to detect. As long as there is a problem I can't really ignore it even as you say it may be only in your case. But, you know... the update was just pushed yesterday so it's better to be safe than sorry. Definitely wouldn't like to have the addon page full of 1 star reviews because of a stupid update I did without proper testing.

That being said... I tested with around 300 tabs... both loaded and unload. When they were unloaded I had under 2 GB o ram usage and nothing special was hapeing... then of course, after I tried to load all of them Firefox jumped to around 8 GB of RAM usage, but that's just because of the tab loading and not caused by the addon I would say. Then, as much as I tried... no CPU spikes and memory... well that oscillated around 1 GB RAM but not really that much as in your case. But yeah... I do have 32 GB of RAM and a 6 core / 12 threads CPU so probably I might not notice it. Of course, at the same time I would say that very few people really go that high with tab count.

So yeah... for the moment it's still a mystery what exactly is wrong. I will keep investigating it, and if I find any solution I will update this thread.

**Comment by ipnoz** [comment]
Hi.
I've got the same problem with your addon, I get huge memory used when the auto-save sessions functionnality is enable (every 15s).
I'm on debian 9.6, firefox 64.0.2 x64.
It's appear when the profile with your addon is idling, the Webextensions process of the profile can up to 2.7 G of RAM used (maybe more...) after a few minutes, 15-30. No need to have many tabs, 4 open is enough. I found that I just need to close a tab and reopen a new one, and the Webextensions process get back to 70k of RAM used.
When the auto-save sessions functionnality is disable, no problem at all... But I need an auto-save sessions :-/

**Comment by ReDEnergy** [comment]
Then there's clearly a serious issue in the last update. I will revert everything back to normal with an update today. I will do an extensive testing to find what exactly caused everything.
Thanks a lot for reporting, and I'm really sorry about a all this. I just hope that very few people were affected by it.

**Comment by agadino** [comment]
Just a message to thank Gabriel for having made this great tool and for his effort to constantly pay attention to all our suggestions. Thank you very much.

**Comment by ReDEnergy** [comment]
Thank you as well @agadino for using the addon. I hope you are not having the same issue with high RAM usage, no?

**Comment by agadino** [comment]
No, it's not a sensible difference in ram consuming, for me, turning on/off auto-save. Anyway I set the save interval at 600seconds, 10 minutes are a good time interval for that feature, for me

**Comment by TehCorwiz** [comment]
Hey, just wanted to chime in that Firefox 65.0 was just released and one of the updates was that the `about:performance` page now shows per-add-on memory usage. Personally, with auto-save on and ~100+ tabs (only a few actually loaded) Session Sync seems to be using 3.7MB, which is pretty reasonable.

![about-performance](https://user-images.githubusercontent.com/1701174/51949982-ced05000-23fc-11e9-9d8f-4e440aa530a1.png)

@ipnoz @hervis73 Can you update Firefox to version 65 and check the [about:performance](about:performance) page while you're experiencing this issue?

**Comment by ReDEnergy** [comment]
@TehCorwiz Thanks a lot for point it out. I looked in about:about for some debugging information but I have no idea why I missed that page. (I'm usually using Developer Edition which is actually 2 versions ahead so I should have noticed it). I will be checking myself further to see if there's anything unusual happening.

**Comment by ipnoz** [comment]
> @ipnoz @hervis73 Can you update Firefox to version 65 and check the about:performance page while you're experiencing this issue?

Hi.
Well I tryed with firefox 65, I still get the issue. When I check about:performance, your plugin is normal, the max memory used is about 2Mo...

**Comment by ReDEnergy** [comment]
Well.. I was expecting at least the memory information to mirror what it's happening. Having only 2 MB of data but then the addon actually using multiple GB of data... that's stupid. I suspect that there might be something else related to the Firefox profile somehow involved. 
Trust me... as much as I would like to fix this stupid bug I have no real information on why it is triggered for some users and for others doesn't. At the same time I can't really disable the functionality for all the users. I'm out of ideas... as much as I look over the code I can't find a real problem from 3.10 to whatever future version and as much as I try to mimic the behavior I'm out of luck. 

Can you please also check the behavior when the Favicon service is disabled (it's responsible with Favicon request from each tab). Basically it's the only reason I might suspect something weird might be happening. 
![image](https://user-images.githubusercontent.com/1395510/52165027-c8471e80-2703-11e9-8e3a-1d331b991e6a.png)
I'm really sorry that I can't do anything more. If you want the only thing I can do is to get you a signed 3.1.0 version that was working, but with a bigger version so that the update won't overwrite it when you restart the browser.

**Comment by SVeeee** [comment]
Hi, 
I face the same issue on FF 65.0 on macos. I have had major memory leaks in FF since a month or so, that would bring my whole machine to a crawl, the disk swapping like crazy. 
I stopped using FF because it was simply unusable, until I finally narrowed it down to two extensions, sessionsync and the lilo search engine extension. 

When sessionsync extension is active, the FirefoxCP WebExtensions process takes more and more memory (It was at 2gigs this afternoon at some point). The phenomenon is especially obvious on waking up my mac. And while FF is hogging memory, in about:performance the plugin shows miminal ram usage.
Everything runs normally normally if I deactivate the plugin.

**Comment by ReDEnergy** [comment]
@SVeeee thanks for reporting the issue also. It's pretty obvious that's there an issue somewhere but as much as I want to clear it out I have no freaking idea how. Trust me, if I could have reproduced the issue I would've solved it right away, but as much as I try, I simply don't understand what exactly triggers this behavior and when exactly. The code doesn't tell me anything as well, I looked over it a dozen times and have no clue what the hell it is happening and why.

By any chance have you tried disabling the Favicon service/History saving and check if the same thing still happens ?

I will keep looking into it... maybe I will be luck at some point like I was with a previous bug that as well it was impossible to reproduce till someday a few month later it happened out of nowhere and I was able to detect and fix the issue in a few days.

**Comment by ReDEnergy** [comment]
Think I managed to reproduce it after all... Got highs of 9GB+ RAM (and keeps going up) from the auto-saving feature on with disabled favicon service... so at least I know that's definitely not be the issue (not that other haven't reported the same thing).

**Comment by ReDEnergy** [comment]
Soo yeah... basically I just found out that the reason is not my code but somehow something the API that I used to saved auto-history.

**Basically, a simple API line like the one bellow triggers the issue**
```js
browser.storage.local.set({ 'history' : HISTORY_OBJECT});
```
Why is it happening having in mind that the HISTORY_OBJECT stays sort of constant (not really, but not that different also)... have no idea at all. Seems to be a strange issue, caused by memory saving inside Firefox, but the main problem is that it's not triggered 100% of the time. I find it very random, only in certain unknown conditions the bug triggers. 

Having notice that, I realized that I do tend to save again the same thing again and again (at least 90% of the data was basically the same) so I optimized this a lot. Theoretically, before the history data was somewhere around 1-2MB ... let's say 10MB but never really close to those 100s of MB or even GB of data. That's why I don't understand why RAM skyrockets like that.

I tested... basically running thousands of saving actions over a short amount of time.
Some benchmarks:
### v3.1.6 : 10000 saves ###
5GB... or 10GB... or 30GB... got really strange random results but one thing is clearly... there's a huge amount of RAM used
### v3.1.8 : 10000 saves ###
Didn't manage to go higher than **1.5GB RAM**
[Download beta release from bere](https://www.dropbox.com/s/wg4ov5rceci1hsh/session_sync-3.1.9b-fx.xpi?dl=0)

### Soo.... Is the problem solved? ###
Certainly not! But I think is shouldn't be as noticeable anymore. 
There seems to be no real explanation for this. It happens only when certain unknown conditions (I least I can't figure out them) are met and only if Firefox is not aggressively enough with RAM consumption. 
Sadly I don't think I can do anything more than what I did in v3.1.8. I will investigate it further but I really have no idea for the moment.

### Any chance to be solved in the near feature? ###
Seems that Firefox 66 will start using IndexDB instead of localStorage for addon storage. This will be an automatically change that will not affect addons in any way but will greatly improved RAM usage as well as performance.
See more here: [Extensions in Firefox 66 - Major Performance Improvements for Storage](https://blog.mozilla.org/addons/2019/02/15/extensions-in-firefox-66/)

### Please download the beta release and let me know if the problem is still ... that problematic  ###
[v3.18 Beta release](https://www.dropbox.com/s/wg4ov5rceci1hsh/session_sync-3.1.9b-fx.xpi?dl=0)

I will updated the official version (on **Addons Mozilla**) once I test the beta myself a few days more to be sure I didn't miss something (made quite a few chances on the history side so better to be sure that everything works as expected)

**Comment by ipnoz** [comment]
I've tested v3.19b all the day, and it's much better in RAM consumption, indeed. I never seen more than 650Mb for the web-extension when my profile idling.
You are in the right way :)

**Comment by ReDEnergy** [comment]
Official fix [v3.1.10](https://addons.mozilla.org/en-US/firefox/addon/session-sync/versions/) was released.
Until Firefox fixes the saving bug in the API sadly I can't do anything more. 
Having in mind that it might be a garbage collection error from Firefox the updated version might not trigger the bug anymore or even if it's present it should be kept quite low.

**Comment by hsantanna** [comment]
> @hsantanna are you talking about that beta v3.1.9b? or the official 3.1.6 version ?
> Today I will launch an official update version but it's similar with **3.1.9b**. If you're talking about the latest version, then sadly I simply have no any other solution for this problem unless Mozilla fixes the memory leak.

I'm using the official, not beta.
Sorry, I should have mentioned that and should have tested the beta before reporting it.

The good news is that I tested the new version released today, enabled auto save and couldn't perceive any memory usage increase since I enabled auto save.

Thank you for your great work on this addon @ReDEnergy! Congrats!

**Comment by ipnoz** [comment]
As I mentionned, the RAM issue is still there, but less impacting.
@ReDEnergy did you report this issue to Firefox dev ? Maybe they have an explaination about ?

**Comment by ReDEnergy** [comment]
@ipnoz Yes, but sadly at this moment I would simply have 2 options... Remove the Auto-Saving feature or leave it like that hoping that people will restart the browser once a day (and not keep it running for 5 days in a row). Of course the memory impact is directly related to how often the auto-save feature updates. If you put it like 30 seconds instead of 10 second then if any kind of memory issue happens it will take 3 times as long to get to the same level.

Regarding reporting the issues, sadly I was not able yet to do that since I have to create a demo extension and I simply didn't have time for it. But of course... I might not have this fixed ever unless I report it so I guess I should do that ASAP.

**Comment by hsantanna** [comment]
Maybe auto save setting should be disabled by default, and the frequency should be set to a higher value by default.

I don't use auto save, so I will keep it disabled here.

**Comment by ReDEnergy** [comment]
Probably fixed long time ago. Will close until someone notice anything else strange.
