### ISSUE TITLE
A problem about New version

### ISSUE THREAD

**Issue by FatesifaeveM** [ReDEnergy/SessionSync#70]
Because of my poor English, maybe I can't explain my questions clearly.
Well, I have some problem in new version.
Because of the big error happen in firefox for the past few days!
I update my firefox version from 54 to 66.0.5!
And renew all extensions I use in the same time.
I encounter a problem for new version:
(1)
I had turned on the lazy loading restore.
But the past saved sessions couldn't been auto redirected to normal web.
It would stay in the condition like ↓ 
—————————————————————————————————————————
AXELYZE - 20周年!『機動戦艦ナデシコ』YOU GET TO BURNING Cover - YouTube
moz-extension://70d9bc9f-5ac3-45f5-b824-f2784a585e96/data/lazy/lazy.html?state=redirect&title=AXELYZE%20-%2020%E5%91%A8%E5%B9%B4!%E3%80%8E%E6%A9%9F%E5%8B%95%E6%88%A6%E8%89%A6%E3%83%8A%E3%83%87%E3%82%B7%E3%82%B3%E3%80%8FYOU%20GET%20TO%20BURNING%20Cover%20-%20YouTube&url=https%3A//www.youtube.com/watch%3Fv%3DSNvJJlRnA2s&favIconUrl=https%3A//s.ytimg.com/yts/img/favicon-vfl8qSV2F.ico
This page is used for lazy loading Session Sync restored pages
If the page was not loaded automatically please check that lazy loading is enabled in addon configuration panel.
Sadly, Firefox Addon API prevents loading certain URL types. This is not an addon issue but and API limitation.

    chrome: URLs
    javascript: URLs
    data: URLs
    file: URLs (files on the filesystem)
    priviledged about: URLs
—————————————————————————————————————————
Although I can use the title and google to search them, or cut and post the useful information from the string to restore them.
I have more than hundreds of sessions in a window and have some windows like that.
Maybe totally have around thousand session like that.
I think I don't have enough time and stamina to correct them one by one. 
Have any method to correct them?
Thank you!

If there is any offence please forgive me.
Please tell me what things that I should offend you if I had done.
I will apologize for it!
Sorry for my poor English!

**Comment by ReDEnergy** [comment]
Not really 100% sure I do understand the actual bug.
So first of all...
1. Does this happen whenever you open a certain session? Every single time?
2. Do you mean that the stored bookmarks are saved with that type of new URL ?

Can you please confirm that session saved in Bookmark Manager have the correct URL as they should. I mean does the bug actually affected the Bookmarks or is just when you restore a certain session.

I certainly hope that the bookmark storage was not affected by any way but if that happened I will clearly do everything I can to correct everything. But I need more in depth information if the actual URL from the bookmarks is changed or not.

Please contact me directly over the email so that we can talk faster. You can find my email on the addon page or simply click on the **Feedback** button from the menu.

![image](https://user-images.githubusercontent.com/1395510/57951388-98a6d580-78f2-11e9-8de3-2d8dae5fc04a.png)

**Comment by ReDEnergy** [comment]
Basically I want you to tell me if the URL from Bookmark Manager (CTRL + SHIFT + B) from a saved session tab is as you would expect or somehow because of a bug was saved wrong and it's that messed up URL used for lazy restoring.

![image](https://user-images.githubusercontent.com/1395510/57952008-89288c00-78f4-11e9-97c0-b9c97f6f0c67.png)

Does the location input look like a normal URL or it looks like what you pasted there ?

I mean... if you can open the bookmark using the bookmark manager then probably I'm missing something and I didn't understand exactly what happened.

**Comment by FatesifaeveM** [comment]
I afraid that the mail didn't send to you, so I post at this too.
It becomes a mess in the bookmark too!

![0000](https://user-images.githubusercontent.com/50743841/57965517-ce41d200-7977-11e9-8418-f1814e2be8b6.png)
![0001](https://user-images.githubusercontent.com/50743841/57965605-04338600-7979-11e9-8aa2-3b6454e0f4eb.png)

**Comment by FatesifaeveM** [comment]
Sorry, I forgot to reply the other two questions!
The condition don't occur for new saved sessions. (Even they are lazy restoring sessions)
I think it just happen at the lazy restoring session saved at old version.

**Comment by ReDEnergy** [comment]
I'll provide a fix for this as soon as possible. Thanks for clarifications.

**Comment by FatesifaeveM** [comment]
It's very grateful that you can solve this question.

**Comment by ReDEnergy** [comment]
Fix was provided
