### ISSUE TITLE
SessionSync Popup unusable in FF Wayland

### ISSUE THREAD

**Issue by covertg** [ReDEnergy/SessionSync#78]
Reporting from Arch Linux running GNOME 3.32.2 under Wayland 1.17.0, with a maybe niche but very limiting bug. When running FF in native Wayland mode (i.e. with the environment variable `MOZ_ENABLE_WAYLAND` set to 1), SessionSync is unusable through the normal popup box that should appear when clicking its icon in the toolbar:
- UI elements are not clickable/don't respond
- Screen edge detection is off; i.e. with FF maximized, most of SessionSync is off the screen

SessionSync does still work fine in full window or tab mode. And when running FF through XWayland (with the environment variable switched off), behavior seems normal.

One reason that native Wayland mode is appealing is for hidpi devices: with fractional scaling enabled (e.g., 125%), running FF through XServer results in blurry fonts and icons.

**Comment by ReDEnergy** [comment]
Sadly this is 100% not an addon bug but an WebExtensions API but. The popul is a standard interface behaviour that you can use for accessing addons UI. As long as the UI behaves normally (in Tab View and Window View) then it's 100% sure that it's a bug from the API, because all the views use the same code.
Sadly there are a few issues with the Popup even on windows or probably all the other platform and Mozilla seems to ignore them completely. For example dragging an element over an empty area can in the popup can block the UI rendering. It's really strange but there sure got to be something odd on how they implemented the Popup because even if it is suppose to load webpages it seems to have some extremely strange limitations.

Regarding the fonts and icons... Well let's say that for icons things might make sense (although I have them with 256 x 256 so I don't really expect to be a resolution problem), but for the font that makes no sense at all. Does it happen also only in the Popup view or in the 3 views. Try to change the scaling of the UI for each area and see if anything different happens. The thing is I scale everything with some standard font settings (I don't render sprites :D) so everything should be able to scale extremely smooth without any problem.

Thank you for all the detailed explanation but I really can't do anything about it sadly. Thanks for using the addon though.

**Comment by mehdisadeghi** [comment]
I'm on archlinux/gnome too. However since I use xorg I don't have this problem. And thanks for the extension. It is extremely helpful.

**Comment by ReDEnergy** [comment]
Thanks @mehdisadeghi for the info. That further indicates that there's a problem within Firefox or the API and not something that I can fix somehow myself. Thanks also for using the addon.
Since I can't do anything about this bug, I will close it for the time being.
