### ISSUE TITLE
Add support of tab groups

### ISSUE THREAD

**Issue by inaniyants** [ReDEnergy/SessionSync#8]
Currently all tabs in all tab groups interpreted as current session.
It would be great if session-sync will interprete current tab group as current session, and allow to save every tab group into separated bookmark folder.

It could be a simple button something like "Save all groups", if there are any of groups, and a checkbox which will be named like "Show tabs from all groups" - it will enable user to see all tabs in current session menu, where will be ui divider between groups.

**Comment by ReDEnergy** [comment]
I'll see what I can do. Not very sure if saving all of them inside the same session is the best approach because usually groups should hold different categories of tabs and mixing them even with a separator might not be the best idea. Groups can have a name just like a session, and saving them this way I won't be able to save that information too.
Then again, a new level of indirection is not an awesome solution as well because it's harder to implement and can create confusion when saving a session. I'm mostly biased towards the second solution.

Having in mind that there are very few people that use groups instead of window I won't consider this a top priority but I might be able to add a simple checkbox to save groups as separated sessions (like windows are treated right now) for now. Let me know what you think.

Thanks for the feedback.

**Comment by inaniyants** [comment]
> Not very sure if saving all of them inside the same session is the best approach because usually groups should hold different categories of tabs

There is some misunderstanding: 
That is  exactly, that I am suggesting: to save tabs only from current group by default (not all groups, as it works currently) - that is the first step that could be applied without increasing difficulties in development and UI.

>with a separator might not be the best idea. Groups can have a name just like a session, and saving them this way I won't be able to save that information too.

Not saving, but just showing them in Current Session UI separately, when user checks suggested "Show tabs from all groups".

**Comment by ReDEnergy** [comment]
Thanks for clarification. Your solution, it's far more simple than what I though initially and quite good. Like you said it shouldn't be to difficult so I will try to add support for it in the next version.

**Comment by the42** [comment]
Heads up for "I like to see that too"

**Comment by fturcheti** [comment]
This would be a great feature, but now that [Tab Groups will be discontinued](https://support.mozilla.org/en-US/kb/tab-groups-removal), it seem to be a waste of time.

As a side note: I'm trying Session Sync as a replacement for Tab Groups.

**Comment by ReDEnergy** [comment]
Ok... Thanks for the heads-up. I didn't know. Since the Tab Groups feature will be removed there won't be any groups to be saved. I will let the issue opened for a while maybe I can figure something out.

**Comment by iShyboy** [comment]
We have a great addon for that, and it's no different from the default, maybe better in a new future.
So, no harm in the issue. 
https://github.com/Quicksaver/Tab-Groups/

**Comment by ReDEnergy** [comment]
True. And since it's supported by such a great addon developer, I will definitively try add to support in a future release.

**Comment by fturcheti** [comment]
This is good news!

**Comment by ReDEnergy** [comment]
This feature won't be implemented since no further support for tab-groups will be available. Firefox will deprecate advanced addon and thus tab-group feature might not be possible anymore. Also Quicksaver announced that he will no longer support development of firefox addons (http://fasezero.com/lastnotice.html) since Mozilla decided to shift towards a less advanced addon ecosystem throught the WebExtensions API.
