### ISSUE TITLE
Nothing but window full of blank tabs

### ISSUE THREAD

**Issue by Zamlet** [ReDEnergy/SessionSync#80]
Hi - just installed SessionSync a few weeks ago and hadn't really used it until today.  I have Firefox 69.0.1 (64-bit) running under LInux Mint 19.2 (Tina) with SessionSync 3.1.12 installed.  But it doesn't seem to be saving the sessions properly.  It saves the right number of tabs, with lazy loading enabled, and the tabs look like they should go to the right places, but when I bring the tab forward and the lazy loading kicks in, the URL is quickly replaced with "about:blank" and the page never loads. 

To reproduce:
1. Open several tabs.  They don't have to be fancy URLs.  www.google.com works fine.
2. Click on SessionSync in the toolbar. "Active session" window is displayed.
3. Click the heart icon to save the session and then click Save.  A new saved session is created with the current timestamp.
4. Quit Firefox, then relaunch it.
5. Click on SessionSync in the toolbar.
6. Click on saved session from step 3 to select it, then click Restore in new window.  A new window is opened with however many tabs you saved in it, with only the first one actually loaded (correctly) due to lazy loading. Displayed titles on other tabs look like URLs.
7. Click on any other tab.  SessionSync's lazy loading information page appears briefly, then the URL in the address bar (beginning with moz-extension:) is quickly replaced with "about:blank" and contents of tab disappear.

I have several other add-ons installed so it is possible there is some sort of conflict with one of them.  My first suspicion would be Group Speed Dial, but I have no evidence to support that.  If there's any other information you need, feel free to ask.

**Comment by ReDEnergy** [comment]
This is definitely a really strange behavior. Everything you explain is ok... but until that about:blank. I don't really understand why and from where it appears, because I don't think I do that in the addon myself.

One thing that is important to check if you can is if the links were saved correctly and if things work ok once you disable the lazy loading.

1. So. first of all... do the tabs saved point to the correct page. If you open any of them manually do open the expected page?
2. Second, if 1 is ok, dlease disable the lazy-loading from the options. and try to restore everything a session and see if everything works as expected. If so, that means that saving is done properly, and the only problem is actually the lazy loading behaviour.
3. If thing are manually saved, restarting the browser shouldn't do anything special so a restart should not really influence anything anyhow.

![image](https://user-images.githubusercontent.com/1395510/66708777-e4a15d80-ed5e-11e9-854c-987e20c29c81.png)

I will check more about this myself but since this is a strange case and I don't really know anyone having this issue, I will assume that there's a strange interference somewhere that causes all this. I will check with Group Speed Dial if it does anything wrong.

**Comment by ReDEnergy** [comment]
Just tested with Group Speed Dial... everything seems to be working just fine. That doesn't mean there might be no problem, but I might have a hard time find what is really the cause to all of this.
