### ISSUE TITLE
Firefox 72.0.2

### ISSUE THREAD

**Issue by agadino** [ReDEnergy/SessionSync#83]
Looks like Session Sync doesn't work with latest Firefox update

**Comment by ReDEnergy** [comment]
Hi @agadino. I don't think there can be any issue with Firefox itself. I use Firefox 73 and works very well. I used 72 for more than 1 month and it worked as it should. Maybe you can describe exactly what doesn't work because I don't think it's a problem with Firefox.

**Comment by agadino** [comment]
It only opens a little window and won't show the web pages names. I reinstalled FF 72.0.1 and worked fine; reinstalled 72.0.2 and again the same problem. I'm temporarily using FF Portable 72.0.1 and it works fine.
There's another addon that stop working with 72.0.2, called Shortcuts for Google (same issue, it shows a little blank window instead the full one with icons)
I'm attaching a couple of screenshots, both with SS working and how it now appears with FF72.0.2

![sessionsync_ERROR](https://user-images.githubusercontent.com/33963054/73063488-2df56300-3e9f-11ea-9c90-d94b49df66ff.jpg)
![sessionsynk_OK](https://user-images.githubusercontent.com/33963054/73063492-2e8df980-3e9f-11ea-9afb-bc43896ec421.jpg)

**Comment by ReDEnergy** [comment]
This is definitely strange... I tried right now to run 72.0.2 and works with no problem
![image](https://user-images.githubusercontent.com/1395510/73064737-9269ef80-3eaa-11ea-9e31-e27d0e68e901.png)

There's an error in your case but I don't know if it's because of Firefox itself or because of something else, and sadly I don't think I can do anything about this unless I find a specific reason for why it would happen. Like I said, I use the Firefox Developer Edition (same as Beta).. so 73 and works there with no issue, so it can't be an incompatibility after 72.0.2

**Comment by agadino** [comment]
Thank you. So it must be something related to my computer or OS.. I'll try with 73 Beta (73 official Italian is not out yet), I'll let you know

**Comment by agadino** [comment]
It works with portable 73 Beta; I'll wait for the standard stable 73 hoping the upgrade will solve the issue
