### ISSUE TITLE
Is there any way to edit the active session?

### ISSUE THREAD

**Issue by jayhorowitz** [ReDEnergy/SessionSync#98]
MacOS, Firefox 83: When viewing the active session, clicking on any tab bring it to the front. There is no right click context menu.

Is there any way to, for example, close currently active tabs from within SessionSync?

**Comment by ReDEnergy** [comment]
Yes there is but it's very stupid (because I forgot to add a context menu to that panel as well). There is a feature request for that already and I plant to add support in the future for it.

The way you can currently close a tab is just drag and drop it into the trash.
![image](https://user-images.githubusercontent.com/1395510/100034610-3bec7b00-2e05-11eb-8213-748d0a61a03a.png)
